# Nome do workflow (aparecerá na aba Actions)
name: CI Simples
# Eventos que disparam o workflow:
# - push (quando algo é commitado)
# - pull_request (quando há PR)
on:
 push:
 branches: [ dev ] # dispara apenas quando o commit é na branch dev
 pull_request:
 branches: [ dev ] # dispara quando há PR para dev
jobs:
 # Definindo um job chamado "build"
 build:
 runs-on: ubuntu-latest # ambiente que o GitHub usa (máquina Linux)
 steps:
 # 1. Baixar o código do repositório
 - name: Checkout do repositório
 uses: actions/checkout@v4
